"""empty message

Revision ID: 4ad3fea6ec81
Revises: 601c7853effb
Create Date: 2021-02-05 10:02:37.849167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad3fea6ec81'
down_revision = '601c7853effb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mfg_id', sa.Integer(), nullable=False),
    sa.Column('lot_num', sa.String(length=30), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('cofa', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reagent_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('expiry_dur', sa.Integer(), nullable=False),
    sa.Column('expiry_type', sa.String(length=10), nullable=False),
    sa.Column('container_size', sa.Float(), nullable=False),
    sa.Column('container_units', sa.String(length=10), nullable=False),
    sa.Column('requires_qual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reagents', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('reagents', 'reagent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reagents', sa.Column('reagent_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('reagents', 'id')
    op.drop_table('reagent_templates')
    op.drop_table('manufacturers')
    op.drop_table('lots')
    # ### end Alembic commands ###
