"""empty message

Revision ID: 601c7853effb
Revises: 
Create Date: 2021-02-01 16:34:19.041593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601c7853effb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reagents',
    sa.Column('reagent_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('reagent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reagents')
    # ### end Alembic commands ###
