"""empty message

Revision ID: b28ef21a36be
Revises: 4ad3fea6ec81
Create Date: 2021-02-05 12:57:29.821540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28ef21a36be'
down_revision = '4ad3fea6ec81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('temp_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'temp_id')
    # ### end Alembic commands ###
